Check for null primary key instead of index
When there is no primary key it return null
```
java.lang.NullPointerException: Cannot invoke "org.h2gis.utilities.Tuple.second()" because "primaryKey" is null
	at org.noise_planet.noisemodelling.jdbc.DelaunayReceiversMaker.fetchCellSource(DelaunayReceiversMaker.java:499)
	at org.noise_planet.noisemodelling.jdbc.DelaunayReceiversMaker.generateReceivers(DelaunayReceiversMaker.java:547)
	at org.noise_planet.noisemodelling.jdbc.DelaunayReceiversMaker.run(DelaunayReceiversMaker.java:139)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:344)
	at org.noise_planet.noisemodelling.scripts.Receivers.Delaunay_Grid.exec(Delaunay_Grid.groovy:364)
```